### ISSUE TITLE
Could not search this plugin

### ISSUE THREAD

**Issue by oksep** [Shrugs/react-native-snippets#11]
**Sublime 3  Console**  could not search this plugin

**Comment by shrugs** [comment]
![image](https://cloud.githubusercontent.com/assets/1535001/16738970/02814f1a-4766-11e6-9f92-c52156b7f582.png)
visible on my end, do you have more information or thoughts on why this could be happening to you?

**Comment by pallzoltan** [comment]
![screen shot 2016-07-15 at 14 05 41](https://cloud.githubusercontent.com/assets/301728/16873717/40f412a0-4a95-11e6-919a-c6881593f051.png)

I don't see it either...

**Comment by shrugs** [comment]
That's pretty bizarre! I doubt it's installed already (if it's installed it doesn't show up).

I see the package just fine on Package Control's website, which makes me think I have everything configured correctly. https://packagecontrol.io/packages/react-native-snippets

I don't really know what to suggest, to be honest.

**Comment by digitalmaster** [comment]
Same issue here.. can't find it. :(

**Comment by digitalmaster** [comment]
whoops.. nvm.. already had it installed 🙈
