### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by Nicolas-Menettrier** [Shrugs/react-native-snippets#12]
All in the title, nice work 👍

**Comment by shrugs** [comment]
Added this to the project for this repo. I don't use atom, however, so I don't want to guarantee that I'll be able to work on this any time soon.

Could we use https://atom.io/packages/atomizr or similar to automatically convert these snippets to the atom format?

**Comment by Nicolas-Menettrier** [comment]
Work well with atomizr, I can share my snippets.cson if you want ?

**Comment by shrugs** [comment]
Nice! If you want to submit a PR that adds the atomizr output, I can start looking into how to publish to atom's package manager.

**Comment by Nicolas-Menettrier** [comment]
#13

**Comment by shrugs** [comment]
Published as `react-native-snippets-horse` on the atom package manage, thanks for the help!
