### ISSUE TITLE
Where exactly are these snippets installed? :)

### ISSUE THREAD

**Issue by chocobuckle** [Shrugs/react-native-snippets#17]
I'd like to edit some of them, but I can't seem to find them when using PackageResourceViewer. Any help would be much appreciated.

**Comment by shrugs** [comment]
Mine are available at `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/react-native-snippets`, let me know if they're not there on your machine!

**Comment by chocobuckle** [comment]
@Shrugs I'm on Windows, but your answer led me down the right path - pun intended! :)

For any other Windows users who might be wondering what the answer is...

```C:\Users\%USERNAME%\AppData\Roaming\Sublime Text 3\Installed Packages\react-native-snippets.sublime-package```

I was originally checking ```C:\Users\%USERNAME%\AppData\Roaming\Sublime Text 3\Packages\User\``` ...to no avail. But all good now. Thanks for your hard work - much appreciated! :)

**Comment by wzup** [comment]
@shrugs 

There is no such directory on `Ubuntu 16.04.4 LTS xenial`:
> bash: cd: /home/user/Library/Application Support/: No such file or directory

There is nothing in `~/.config/sublime-text-3/Packages` either.

Where is it installed?
I want to change default placeholder for `styles.` to `css.`:
```
from: <View style={styles.}></View>
to: <View style={css.}></View>
```

**Comment by shrugs** [comment]
Downvoting my macOS specific comment for not mentioning Ubuntu isn't very nice.

I would recommend reading the docs for information on your specific system.

https://www.sublimetext.com/docs/3/packages.html

Regardless, this will not be a problem specific to react-native-snippets, as it would affect any package you install through package control.
