### ISSUE TITLE
ES2015 class?

### ISSUE THREAD

**Issue by rclai** [Shrugs/react-native-snippets#6]
I see that the `rncc` command yields a class component according to the source code, but every time I do it, it's still giving it to me in this format: `React.createClass`, has this been pushed out to ST3?

I'm seeing v0.1.0 according to the package manager but it's v0.2.0 here.

**Comment by shrugs** [comment]
Good question; I assumed the new GitHub release would propagate to Package Control, but apparently I need to do something else. Will investigate and fix ASAP.

**Comment by shrugs** [comment]
@rclai Thanks for the heads up, issue's been fixed; didn't realized I had an invalid semver version in the latest release. Package Control should update the package automagically next time it updates itself.

Cheers!

**Comment by rclai** [comment]
Thanks!
