### ISSUE TITLE
rncc snippet deprecated warning

### ISSUE THREAD

**Issue by shivamsinha15** [Shrugs/react-native-snippets#8]
RNVersion:

```
  "dependencies": {
    "react": "^0.14.8",
    "react-native": "^0.25.1",
 }
```

**Importing React from react-native has been deprecated in 0.25.1. It will stop working in 0.26.**

> Warning: ReactNative.createElement is deprecated. Use React.createElement from the "react' package instead.

```
import React, {
  StyleSheet,
  View,
  Text
} from 'react-native';

class ${1:${TM_FILENAME/(.+)\..+|.*/$1/:MyComponent}} extends React.Component {
```

Instead take the following approach:

```

import React, { Component } from 'react';

import  {
  StyleSheet,
  View,
} from 'react-native';

class ${1:${TM_FILENAME/(.+)\..+|.*/$1/:MyComponent}} extends Component {
```

It also looks cleaner if you use just import Component instead of using React.Component.

**Comment by shrugs** [comment]
merged #9 , thanks!
